# Generated by Django 3.0.5 on 2020-05-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OR_CU',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Calories',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Image',
            field=models.ImageField(default='default.png', upload_to='menu_items', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Vegetarian',
            field=models.BooleanField(verbose_name='Vegetarian'),
        ),
    ]
