# Generated by Django 3.0.5 on 2020-05-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200509_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='BR_Address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='branch',
            name='BR_Name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='category',
            name='CA_Name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CU_Address',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CU_Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EM_BR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EM_EM_Manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Employee'),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_CA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_GluttenFree',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Image',
            field=models.ImageField(default='default.png', upload_to='menu_items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='IT_Vegetarian',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='RC_TotalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='RC_TotalProfit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='RS_End',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='RS_People',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='RS_Start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='TA_BR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Branch'),
        ),
        migrations.AlterField(
            model_name='table',
            name='TA_Code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='TA_Seats',
            field=models.IntegerField(),
        ),
    ]
