# Generated by Django 3.0.5 on 2020-05-29 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_order_or_cu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OR_CU',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Customer'),
            preserve_default=False,
        ),
    ]
